### PR TITLE
WiP Astor repair

### LINKED ISSUE #636: add ingredientstrategy parameter to Astor-JGenProg
This strategy should give better results:

    -ingredientstrategy fr.inria.astor.test.repair.evaluation.extensionpoints.ingredients.MaxLcsSimSearchStrategy

Version to take is 4b9e6945827972434782e3201f03aa74c3db26f8

Thanks to @chenzimin

### PR DESCRIPTION
**Pull request by btellstrom**
Proposed PR to resolve #636

### CODE REVIEW

**Comment by btellstrom** [comment]
Should I in the future create branches on the Spirals-Team version instead? When I last looked I was unable to create a branch, so I did it in my own fork instead.

**Comment by surli** [comment]
> Should I in the future create branches on the Spirals-Team version instead?

Yeah I'll give you the right for that.

**Comment by monperrus** [comment]
Could you recreate a new PR from a branch located to make sure that CI passes?

**Comment by surli** [comment]
Let's accept it like that for now. We'll continue to discuss in #636 on how to improve test. You now have rights to create new branches of the repo for future PR.

**Pull request merged**
