### PR TITLE
add support to gather all patches produced by different tools in one …

### PR DESCRIPTION
**Pull request by ycaxgjd**
…common list

### CODE REVIEW

**Comment by ycaxgjd** [comment]
Hey, this is for [issue #843](https://github.com/Spirals-Team/repairnator/issues/843)

**Comment by btellstrom** [comment]
This only seems to be a test-file, is there something missing?

Also, there is currently a script that essentially does the [same thing](https://github.com/Spirals-Team/repairnator/blob/134d7db9ff85bf9934b5f26c2a9fc6b2cf3705b2/repairnator/scripts/patched_builds.py) (I missed the issue), but having it in java and auto updating it would certainly be a benefit. If you commit the function itself I'd be more than willing to have a look at it!

**Comment by btellstrom** [comment]
Also, the way our test suite is working at the moment your build should always fail, so it is most likely not due to your addition, but rather because you are working from a fork.

**Comment by ycaxgjd** [comment]
The gathering function should have already been implemented, so I only commit one corresponding test file.

Here are related code:
https://github.com/Spirals-Team/repairnator/blob/master/repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/AbstractRepairStep.java#L95

https://github.com/Spirals-Team/repairnator/blob/master/repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/JobStatus.java#L264

https://github.com/Spirals-Team/repairnator/blob/master/repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/JobStatus.java#L268

**Comment by btellstrom** [comment]
OH! It was per build basis, my mistake! Now I understand.

You have a lot of commented out code in the file. Is that supposed to be there? Also, not sure what the general practice is, but should this be in its own file? It seems that a feature like this should be tested in the same file as the class that creates the patchlist. WDYT?

**Comment by ycaxgjd** [comment]
Hey, Benjamin, you are right. I made some changes, making it more reasonable.

**Comment by btellstrom** [comment]
This looks good, now to the issue of making sure that the CI passes as well... 

Also, are you sure that NPEFix only has 4 patches? I usually get about 1270 when running it on the failingProject.

**Comment by ycaxgjd** [comment]
Yes, 4 patches. I can pass this test file in my development environment. I guess that one kind of Nopol repairs usually gets over 1000 patches.

I am not sure the cause of this CI issue, maybe we could adjust the travis_wait parameter.

**Comment by btellstrom** [comment]
> Yes, 4 patches. I can pass this test file in my development environment. I guess that one kind of Nopol > repairs usually gets over 1000 patches.
Okay, guess I remembered wrong.

Well, I know why the CI is failing most likely, it is because you are working from a fork which means that a lot of our tests can not run properly. I'm just curious how to resolve that issue. I think we'll speak about this later today (worst case scenario, I'll just create a branch that is a copy of your fork, run it through the CI and merge this PR if it passes).

**Comment by btellstrom** [comment]
#853 Passes so this must also pass. Merged.

**Pull request merged**
