### PR TITLE
Option to manipulate the pom-file before calling the maven invoker

### PR DESCRIPTION
**Pull request by btellstrom**
To be able to load snapshots and similar experimental tools, we will need to be able to tell repairnator to use non-maven-central repos. Currently, I am not aware of any way to load a custom pom-model into the invoker, and thus adding these repos into the pom before calling the maven-invoker seems to be the most simple way of doing this.

I put this into a separate PR since I will be adding some tests and messing with the configuration files, and it is a separate feature to NPEFixSafe, although at the moment necessary.

### CODE REVIEW

**Comment by btellstrom** [comment]
It seems that evosuite.org is currently timeouting, which seems to lead to the build erroring due to taking too long. `The job exceeded the maximum time limit for jobs, and has been terminated.` Is at the very end of the raw log.

**Comment by btellstrom** [comment]
Do we have a flaky test?

```
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 13.035 sec <<< FAILURE! - in fr.inria.spirals.repairnator.realtime.TestRTScanner
testRepositoryWithoutCheckstyleIsInteresting(fr.inria.spirals.repairnator.realtime.TestRTScanner)  Time elapsed: 3.101 sec  <<< FAILURE!
java.lang.AssertionError
	at fr.inria.spirals.repairnator.realtime.TestRTScanner.testRepositoryWithoutCheckstyleIsInteresting(TestRTScanner.java:49)


Results :

Failed tests: 
  TestRTScanner.testRepositoryWithoutCheckstyleIsInteresting:49

Tests run: 9, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] repairnator-root ................................... SUCCESS [ 13.592 s]
[INFO] repairnator-core ................................... SUCCESS [ 15.071 s]
[INFO] repairnator-pipeline ............................... SUCCESS [19:18 min]
[INFO] repairnator-scanner ................................ SUCCESS [02:09 min]
[INFO] repairnator-dockerpool ............................. SUCCESS [  4.604 s]
[INFO] repairnator-checkbranches .......................... SUCCESS [  3.286 s]
[INFO] repairnator-realtime ............................... FAILURE [ 14.983 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22:26 min
[INFO] Finished at: 2019-07-05T11:41:14Z
[INFO] Final Memory: 148M/970M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project repairnator-realtime: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/travis/build/Spirals-Team/repairnator/repairnator/repairnator-realtime/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :repairnator-realtime
travis_time:end:057e3316:start=1562325526369763698,finish=1562326875272432247,duration=1348902668549
[0K[31;1mThe command "./.travis/travis-run.sh" exited with 1.[0m



Done. Your build exited with 1.
```

**Comment by btellstrom** [comment]
I believe the failing test might be because our test is relying on a repository that was recently updated, and where they specifically mention that they updated their checkstyle version 3 days ago.

nosan/embedded-cassandra

**Comment by btellstrom** [comment]
This PR should now be done.

**Comment by monperrus** [comment]
LGTM but CI is red. How to fix this?

**Comment by btellstrom** [comment]
The NPERepair test was failing, and I assume it's because I updated the version of maven-repair it is running. Updated the test accordingly now and if it doesn't work I'll revert the update (the version is only relevant for NPEFixSafe) and see if that works.

**Comment by btellstrom** [comment]
One of our tests for checkstyle is currently faulty due to the repository recently starting to use checkstyle. I've ignored the test for now (it was passing before) but if we want to keep a test we should find a new repo that has the same desirable traits as it used to have.

@monperrus It should be done now.

**Comment by monperrus** [comment]
Thanks!

**Pull request merged**
