### PR TITLE
Change the prefix in patch email notifications.

### LINKED ISSUE #804: Prefix automatically generated emails by [repairnator]
Today the emails are prefixed by the name of the tool that generated the fix, e.g., [NopolAllTests]
It would make sense to prefix all emails by [repairnator] and mention the name of the tool later in the email object or email body
what do you think?

### PR DESCRIPTION
**Pull request by btellstrom**
Closes #804.

### CODE REVIEW

**Comment by bloriot97** [comment]
Ready @btellstrom ?

**Comment by btellstrom** [comment]
yes, its ready

**Comment by monperrus** [comment]
Thanks. Will it be deployed automatically?

**Comment by btellstrom** [comment]
No, only the docker-image is currently automatically deployed. I'm wondering whether I should create a webhook to push to repairnator or if I should just periodically check if there is a new version by a cron job or something.

**Comment by monperrus** [comment]
a webhook would be more elegant :-)

**Pull request merged**
