### PR TITLE
change the schema of naming librepair-experiments branches

### PR DESCRIPTION
**Pull request by surli**
branch name should not be identified by the patched buildid as we do not store it in the mongodb. Instead we should ALWAYS use the buggybuildid.

### CODE REVIEW

**Comment by surli** [comment]
@monperrus I need your advice on this one: the current behaviour is to name branches on librepair experiments using either:
- buggy build id + date of the bug + "bugonly" suffix, in case no human patch is found
- patched build id + date of the patch, in case a human patch is found

The problem is, as I don't store the patched build id in the DB, I cannot easily find the associated branch of a buggy build if a patch has been found.
That *should* not be a problem in the future as we also store the URL of the remote branch in the DB, but still I find having two different pattern for naming branch confusing.

WDYT? Should we rely on the old pattern naming or should we change it now for future branches?

**Comment by monperrus** [comment]
Is it possible to to do a massive renaming of old branches? Or do we have to keep two different
naming conventions in the repo (old and new)?

**Comment by surli** [comment]
> Is it possible to to do a massive renaming of old branches?

Yes it's possible. I could first merge the PR, start to use the new naming convention and then use a script to extract the buildid / date and rename from that.
We have to be absolutely sure about our naming format then.

**Comment by monperrus** [comment]
per our discussion.

- we change the naming convention
- we don't rename anything

**Pull request merged**
