### PR TITLE
[WIP]Completing new tasks in issue (#813)

### PR DESCRIPTION
**Pull request by Tailp**
This PR is for completing assigned tasks in issue (#813) . :)

### CODE REVIEW

**Comment by monperrus** [comment]
Very good, but this is all in one single PR.

To practice the concept of "branch by abstraction", please split in smaller PRs as specified in #813

**Comment by Tailp** [comment]
I'll be on that in a new PR :) . For the moment i'll use this [WIP] PR as a CI server for my work.

**Comment by monperrus** [comment]
> For the moment i'll use this [WIP] PR as a CI server for my work.

That's a good practice!

**Comment by Tailp** [comment]
This is just a WIP for issue #813 . It will be broken down and merged in new PR :) .

**Pull request closed without merging**
