### PR TITLE
Rename things related to bears.json file

### LINKED ISSUE #615: Review word "metrics" being used everywhere.
We use the word "metrics" to refer to a set of properties, which includes quantitative and qualitative data. In rare cases, we use the word "properties". I think the latter is better to express what we are referring to, because when I read "metrics", I think on numbers only. For instance, the classes `Metrics` and `Metrics4Bears` have a lot of "info" not related to number. I propose the usage of the word "properties" everywhere. WDYT?
Despite the fact that performing a solution for this issue will affect several different locations in the project, I think this is a good-first-issue.

### PR DESCRIPTION
**Pull request by fermadeiral**
This PR does not close any issue, but it is a start towards the new `repairnator.json` generation (related to #476), which also contributes to close #615.

### CODE REVIEW

**Comment by fermadeiral** [comment]
The build is broken, and I still can't really understand why, so I will leave this PR as WIP until I find a way to fix it.

**Comment by fermadeiral** [comment]
@surli, could you check this PR for me, please, to try to find the issue? I will close this PR if I can't fix that today, because I can't find the problem with it.

**Comment by surli** [comment]
Sorry I did not check this one. I might have a look tomorrow.

**Comment by fermadeiral** [comment]
Don't worry about this one. I will create a new PR and I will do a commit for each refactoring to find what is making the build failing.

**Pull request closed without merging**
