### PR TITLE
added maven-repair repository

### PR DESCRIPTION
**Pull request by btellstrom**
After an email-chain it was decided that we will, at least temporarily, move the [maven-repair](https://github.com/Spirals-Team/maven-repair/) into the Repairnator repository.

### CODE REVIEW

**Comment by monperrus** [comment]
we have to remove .gitignore and .travis* 

and modify the existing travis config to also compile maven-repair.

**Comment by bloriot97** [comment]
Oh it is a big commit, is there anything I need to particularly have a look on?

**Comment by btellstrom** [comment]
@bloriot97 I think the most important thing is that travis-ci is properly set up, with a specific process for repairnator, and a separate process for maven-repair. So, if you check the build in travis you will see that there are two separate processes, from two different scripts. The relevant bit is that these scripts are not odd and that the `matrix` part of `.travis.yml` is properly set up. Since the build is passing after running the testsuite for about as long as usual I'd say it is most likely complete, but a second opinion is also nice.

[Maven-repair](https://github.com/Spirals-Team/maven-repair/) is another project, which for the moment has been transferred to this repository instead (partly for proceeding with #640 ). Also, most of the tools in that repository (if not all) are used in repairnator.

**Comment by bloriot97** [comment]
Ok, it seems good for me. 
Thank you ;)

**Pull request merged**
