### PR TITLE
WIP Fix bug in MavenModelResolver

### PR DESCRIPTION
**Pull request by surli**
Some times it appears that the `SOURCEDIRNOTCOMPUTED` status happens because we do not manage to resolve properly the maven model. This PR tries to fix that issue.

### CODE REVIEW

**Comment by fermadeiral** [comment]
Is this bug still an existing bug?

**Comment by surli** [comment]
Yes the bug still exists.

**Comment by fermadeiral** [comment]
Ok ;/

Do you intend to open an issue for that since it seems there is no fix for that right now?

**Comment by surli** [comment]
Done

**Pull request closed without merging**
