### PR TITLE
Feat: implement pipeline

### PR DESCRIPTION
**Pull request by Tailp**
Hi @monperrus :) , implementation for the pipeline . After this there will be a final PR to update the pipeline docker image.

### CODE REVIEW

**Comment by monperrus** [comment]
The diff is not correct, it contains the commit from master. Bad merge or rebase?

**Comment by Tailp** [comment]
Best that I delete this one and make a new branch again to avoid confusion :) .

**Comment by monperrus** [comment]
if you want to improve your Git skills, you'd better stay in this branch and PR :-)

**Comment by Tailp** [comment]
Good point , thanks :) . I guess I can try it out first. If it takes to long I can do a new branch.

**Comment by Tailp** [comment]
@monperrus hi :) , I tried . It could have been better. The latest commit is "merge from master" actually empty so It should have another message instead. WDYT ? .

**Comment by monperrus** [comment]
diff is still incorrect :-)

**Comment by Tailp** [comment]
@monperrus Hi :) , I think it is now fixed.

**Comment by monperrus** [comment]
Thanks @Tailp !!

**Pull request merged**
