### PR TITLE
Doc: test commit

### PR DESCRIPTION
**Pull request by Tailp**
Related issue (#867)

### CODE REVIEW

**Comment by Tailp** [comment]
@monperrus @btellstrom  Hi, this is a fresh fork from the master and it still appears to be failing by only changing a line in the readme. Maybe I did something wrong or maybe it's still flaky ? :) .

**Comment by btellstrom** [comment]
Forks will never pass the CI. 

We have some tests that require encrypted info, which through travis-ci can not be shared to forks, and thus anything that relies on them will falsely report that the tests are failing. (See #744 )

**Comment by Tailp** [comment]
God bless you @btellstrom , I suspected something like that.

**Comment by btellstrom** [comment]
Since there is already an issue related to this problem and this PR does not contribute anything I'll go ahead and close this as well as the issue.

**Comment by Tailp** [comment]
Please do . Thank you very much for answering :).

**Comment by monperrus** [comment]
added @Tailp to the project so that you can create your own branch there instead of on your fork.

**Comment by monperrus** [comment]
For the record, duplicate of #744

**Comment by Tailp** [comment]
@monperrus Thank you for adding me, :) .

**Pull request closed without merging**
