### PR TITLE
Use config in scanner module

### PR DESCRIPTION
**Pull request by fermadeiral**

### CODE REVIEW

**Comment by fermadeiral** [comment]
@surli, forgeting the another PR by now, is this what you thought? The changes related to the `skip-failing` arg and the `targetFailing` variable will be in the another PR, is that correct?

**Comment by surli** [comment]
> The changes related to the skip-failing arg and the targetFailing variable will be in the another PR, is that correct?

Exactly! But apparently Travis is broken now...

**Comment by fermadeiral** [comment]
It's because of the GitHub ratelimit again...

`13:22:59.138 [main] DEBUG f.i.j.helpers.PRInformationHelper - GitHub ratelimit: Limit: 60 Remaining: 0 Reset hour: 09:33:27
13:22:59.138 [main] WARN  f.i.j.helpers.PRInformationHelper - You reach your rate limit for github, you have to wait Sun Jan 18 09:33:27 EST 1970 to get datas. PRInformation will be null for build 345990212
13:22:59.138 [main] ERROR f.i.s.r.p.s.c.CheckoutBuggyBuild - Error while getting the PR information...
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 9.132 sec <<< FAILURE! - in fr.inria.spirals.repairnator.process.step.TestComputeTestDir
testComputeTestDirWithReflexiveReferences(fr.inria.spirals.repairnator.process.step.TestComputeTestDir)  Time elapsed: 9.132 sec  <<< FAILURE!`

**Comment by surli** [comment]
Rha! I'll open an issue I don't understand why we are so limited

**Comment by surli** [comment]
Are all test about repairnator-scanner passing on your computer?

**Comment by surli** [comment]
Tell me when it's ready ;)

**Comment by fermadeiral** [comment]
> Tell me when it's ready ;)

I restarted the build and now it passed. For me, it's ready.

**Comment by surli** [comment]
Let's merge then

**Pull request merged**
