### PR TITLE
Improve management of arguments in scripts.

### LINKED ISSUE #561: Improve management of arguments in scripts
Each script as its own management of arguments right now: it should be managed in only one file and used in every scripts.

### PR DESCRIPTION
**Pull request by fermadeiral**
This PR intends to fix #561.

### CODE REVIEW

**Comment by surli** [comment]
First feeling: we really don't need a JSON file here, in the examples you provide it's a flat JSON, so a property file would be easier to write here.

**Comment by monperrus** [comment]
Conflict here. Rebase?

**Comment by monperrus** [comment]
Hi Fernanda, what are your plans with those open PRs?

**Comment by fermadeiral** [comment]
> Hi Fernanda, what are your plans with those open PRs?

Hi Martin. I'm closing this one. The other one I will fix the conflicts soon.

**Pull request closed without merging**
